1 ERREUR : CloudWath event tartget
  Creating CloudWatch Events Target failed:
  ResourceNotFoundException: Rule my_custom_event_rule does not exist on
  EventBus default.

  il n'accepte pas le nom paramètré